using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;

namespace TroopDesignerRewritten.Data
{
    internal class TroopDesignerMarketData : IMarketData
    {
        internal static void AutoGeneratedStaticCollectObjectsFakeMarketData(
          object o,
          List<object> collectedObjects)
        {
            ((TroopDesignerMarketData)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
        }

        protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
        {
        }

        public int GetPrice(
          ItemObject item,
          MobileParty tradingParty,
          bool isSelling,
          PartyBase merchantParty)
        {
            return item.Value;
        }

        public int GetPrice(
          EquipmentElement itemRosterElement,
          MobileParty tradingParty,
          bool isSelling,
          PartyBase merchantParty)
        {
            return itemRosterElement.ItemValue;
        }
    }
}
